Simple Blog/config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end
  devise_for :users
  resources :users
  get 'welcome/index'
  get 'welcome', to: 'welcome#index'
  root 'posts#index'
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Simple Blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Simple Blog/app/models/article.rb
class Article < ApplicationRecord
end

Simple Blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user,optional: true
  belongs_to :post
  validates :body, presence: true
end

Simple Blog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, presence: true
  validates :body, presence: true

end

Simple Blog/app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Simple Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:userName])
  end
end

Simple Blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles=Article.all
  end

  def new
  end

  def create
    #render plain: params[:article].inspect
    @article=Article.new(article_params)
    @article.save
    redirect_to @article
  end

  def show
    @article = Article.find(params[:id])
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

Simple Blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_post, :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new

  end

  # GET /comments/1/edit
  def edit

  end

  # POST /comments
  # POST /comments.json
  def create
    @post=Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    if current_user
      @comment.user_id=current_user.id
      @comment.user_userName=current_user.userName
    else
      @comment.user_id=nil
    end
    respond_to do |format|
      if @comment.save
        #redirect_to post_path(@post)
         format.html { redirect_to post_path(@post), notice: 'Comment was successfully created.' }
         format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json

  def destroy
    @post = Post.find(params[:post_id])

    # respond_to do |format|
    #   format.html { redirect_to post_path(@post), notice: 'Comment was successfully destroyed.' }
    #   format.json { head :no_content }
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
    end

  private

    def set_post
      @post=Post.find(params[:post_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @post.comments.find(params[:id])

    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :user_userName, :post_id)
    end
end

Simple Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit

  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(post_params)
    @post.user_id=current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

Simple Blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:userName)
    end
end

Simple Blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

end

Simple Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Simple Blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Simple Blog/app/helpers/comments_helper.rb
module CommentsHelper
end

Simple Blog/app/helpers/posts_helper.rb
module PostsHelper
end

Simple Blog/app/helpers/users_helper.rb
module UsersHelper
end

Simple Blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Simple Blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

Simple Blog/app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with scope: :article, url: articles_path , local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

Simple Blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

Simple Blog/app/views/comments/_comment.html.erb
<div class="media">
  <p  class="postTitle mt-0">
    <strong>User : </strong>
    <% if comment.user %>
      <%= comment.user.userName %>
    <%else%>
      Unknown
    <%end%>
  </p>
  <div class="media-body postBody">
      <p  class="postTitle mt-0">
        <strong>Comment:</strong>
        <%= comment.body %>
      </p>
  </div>

  <% if current_user %>
    <p  class="postTitle">

      <%= link_to 'Delete Comment', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>

      <%= link_to 'Edit', edit_post_comment_path(@post,comment) %>
    </p>
  <%end%>
</div>

Simple Blog/app/views/comments/_form.html.erb
<%= form_with(model: [ @post,@post.comments.build]) do |form| %>

  <!--<p>-->
    <% form.label :userName %>
    <%= form.hidden_field :userName %>
  </p>
  <p>
    <% form.label :body %>
    <%= form.text_area :body, id: :comment_body,class:"form-control" %>
  </p>

  <!--<div class="field">-->
    <!--<%= form.label :user_id %>-->
    <%= form.hidden_field :user_id, id: :comment_user_id %>
  <!--</div>-->

  <!--<div class="field">-->
    <!--<%= form.label :post_id %>-->
    <%= form.hidden_field :post_id, id: :comment_post_id %>
  <!--</div>-->

  <p>
    <%= form.submit class:"btn btn-primary center-block"%>
  </p>
<% end %>

Simple Blog/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<!--<p> <%= @post.title%></p>-->
<% if user_signed_in? %>
  <%= form_with(model: [@post,@post.comments.build],url: post_comment_path,:method => :patch,local: true ) do |form|%>
    <p>
    <%= form.label :comment %><br>
    <%= form.text_area :body, :value=>@comment.body%>
    </p>
    <p>
      <%= form.submit "Confirm edit"%>
    </p>
<%end%>
  <%else%>
  <%= "You Are Loged out " %>
<!--<p> <%= @post.body%></p>-->


  <%end%>
<%= link_to 'Back', @post %>

Simple Blog/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= comment.post %></td>

        <td><%= link_to 'Show', comment %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
          <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>7
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

Simple Blog/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

Simple Blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

Simple Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceBooky</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>articles

  <body>

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   '/' %></li>
          <li><%= link_to "Sign Up",'/users/sign_up' %></li>
          <li><%= link_to "Log in", '/users/sign_in' %></li>
        </ul>
      </nav>
    </div>
  </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <%= yield %>
    <% if current_user %>
  <%= link_to 'Logout' , destroy_user_session_path, method: :delete   %>
    <%end%>
  </body>
</html>

Simple Blog/app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <div class="field">
    <%= form.label :title%>
    <%= form.text_field :title, id: :post_title,class:"form-control" %>
  </div>

  <div class="field ">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body ,class:"form-control"%>
  </div>

  <!--<div class="field">-->
    <%= form.hidden_field :user_id, id: :post_user_id %>
  <!--</div>-->
  <div class="actions">
    <%= form.submit  class:"btn btn-primary center-block"%>
  </div>
  </div>
<% end %>

Simple Blog/app/views/posts/edit.html.erb
<h1 class="text-center">Editing Post</h1>

<%= render 'form', post: @post %>

<p class="text-center"><%= link_to 'Show', @post%> | <%= link_to 'Back', posts_path %></p>

Simple Blog/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1  class="text-center">Posts</h1>

<table  class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.user.userName %></td>
        <td><%= link_to 'Show', post %></td>
        <% if current_user %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>

        <%end%>
          </tr>
    <% end %>
  </tbody>
</table>

<br>

<p class="text-center"><%=link_to 'New Post', new_post_path %></p>

Simple Blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

Simple Blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="postTitle">
  <p>
    User : <%= @post.user.userName %>
  </p>

  <p>
    Title : <%= @post.title %>
  </p>

  <p>
    Body : <%= @post.body%>
  </p>
</div>


<h2 class="commentTitle">Comments</h2>
<%= render @post.comments %>

<h3>Add a comment : </h3>
<%= render 'comments/form' %>

<p class="text-center">
  <%= link_to 'Edit', edit_post_path(@post) %> | <%= link_to 'Back', posts_path %>
</p>

Simple Blog/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :userName %>
    <%= form.text_field :userName, id: :user_userName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Simple Blog/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Simple Blog/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.userName %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% link_to 'New User', new_user_path %>

Simple Blog/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

Simple Blog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  Username : <%= @user.userName %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |

Simple Blog/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<p>Ahmed Itman</p>